#!/usr/bin/env bash
# First-time setup on a fresh Ubuntu/Debian server, and the update command later.
#
#   bash infra/bootstrap.sh https://147-45-224-200.sslip.io
#
# Safe to re-run: Docker is only installed when missing, secrets are only
# generated when infra/.env does not exist yet, and the database volume is never
# touched. Running it again after `git pull` is the normal way to deploy.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$PWD"
ENV_FILE="infra/.env"

PUBLIC_URL="${1:-}"

log() { printf '\n\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m !\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m x\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root: sudo bash infra/bootstrap.sh <PUBLIC_URL>"

# ─── Docker ────────────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker"
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg openssl >/dev/null
  curl -fsSL https://get.docker.com | sh
else
  log "Docker is already installed: $(docker --version)"
fi

docker compose version >/dev/null 2>&1 || die "The Docker Compose plugin is missing."

# ─── Configuration ─────────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  log "Reusing the existing $ENV_FILE"
  [ -n "$PUBLIC_URL" ] && warn "PUBLIC_URL argument ignored; edit $ENV_FILE to change it."
else
  [ -n "$PUBLIC_URL" ] || die "First run needs the address: bash infra/bootstrap.sh https://host"

  case "$PUBLIC_URL" in
    http://*|https://*) ;;
    *) die "PUBLIC_URL must start with http:// or https:// — got '$PUBLIC_URL'" ;;
  esac

  log "Writing $ENV_FILE with freshly generated secrets"
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by infra/bootstrap.sh on $(date -u +%F' '%T) UTC.
PUBLIC_URL="${PUBLIC_URL%/}"

POSTGRES_USER="poker"
POSTGRES_PASSWORD="$(openssl rand -hex 24)"
POSTGRES_DB="poker_league"

JWT_SECRET="$(openssl rand -hex 32)"
INTERNAL_API_TOKEN="$(openssl rand -hex 32)"
ACCESS_TOKEN_TTL=900
REFRESH_TOKEN_TTL=2592000

# Fill in from @BotFather, then re-run this script.
TELEGRAM_BOT_TOKEN=""
TELEGRAM_BOT_USERNAME=""
EOF
  chmod 600 "$ENV_FILE"
fi

# ─── Firewall ──────────────────────────────────────────────────────────────────
# Only if ufw is already active: silently enabling a firewall on someone's server
# is a good way to lock them out of it.
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active'; then
  log "Opening HTTP and HTTPS in ufw"
  ufw allow 80/tcp >/dev/null
  ufw allow 443/tcp >/dev/null
fi

# ─── Build and start ───────────────────────────────────────────────────────────
log "Building images (first run takes a few minutes)"
docker compose -f infra/docker-compose.yml build

log "Starting the stack"
docker compose -f infra/docker-compose.yml up -d

# ─── Report ────────────────────────────────────────────────────────────────────
# shellcheck disable=SC1090
set -a; . "$REPO_ROOT/$ENV_FILE"; set +a

log "Waiting for the API to become healthy"
for _ in $(seq 1 60); do
  if [ "$(docker inspect -f '{{.State.Health.Status}}' poker-league-api-1 2>/dev/null)" = "healthy" ]; then
    break
  fi
  sleep 5
done

log "Making sure a season exists"
docker compose -f infra/docker-compose.yml exec -T api node scripts/init-season.mjs || \
  warn "Could not create the season. Check: docker compose -f infra/docker-compose.yml logs api"

echo
docker compose -f infra/docker-compose.yml ps
echo
log "Site: ${PUBLIC_URL:-see $ENV_FILE}"

if [ -z "${TELEGRAM_BOT_TOKEN:-}" ]; then
  warn "TELEGRAM_BOT_TOKEN is empty: the bot and Telegram login are off."
  warn "Add the token to $ENV_FILE and re-run this script."
fi

cat <<'EOF'

Next: appoint the first administrator. Sign in on the site once, then run

  docker compose -f infra/docker-compose.yml exec api node scripts/grant-role.mjs --list
  docker compose -f infra/docker-compose.yml exec api node scripts/grant-role.mjs "<nickname>" admin

Logs:  docker compose -f infra/docker-compose.yml logs -f --tail=100
EOF
